
CREATE TABLE CSUF_MEMBER
	( CWID		CHAR(9)		NOT NULL,
	  Fname		VARCHAR(15)	NOT NULL,
	  Lname		VARCHAR(15) 	NOT NULL,
	  Address	VARCHAR(40),
	  Phone	CHAR(15),
	PRIMARY KEY(CWID)
);

CREATE TABLE ACCOUNT
(
	CWID CHAR(9) NOT NULL,
	Email VARCHAR(40) NOT NULL,
	Password VARCHAR(30) NOT NULL,
	AType	int NOT NULL,
	PRIMARY KEY(CWID),
	FOREIGN KEY(CWID) REFERENCES CSUF_MEMBER(CWID)
);

CREATE TABLE FACULTY
	( CWID CHAR(9) NOT NULL,
	Title varchar(30) NOT NULL,
	PRIMARY KEY(CWID),
	FOREIGN KEY(CWID) REFERENCES CSUF_MEMBER(CWID)
);


CREATE TABLE STUDENT
(	
	CWID CHAR(9) NOT NULL,
	DNum INT	NOT NULL,
	PRIMARY KEY(CWID),
	FOREIGN KEY(CWID) REFERENCES CSUF_MEMBER(CWID)
);


CREATE TABLE DEPARTMENT
	( Dnum	INT		NOT NULL,
	  Dname		VARCHAR(30)	NOT NULL,
	  Phone		CHAR(15)		NOT NULL,
	  Location	VARCHAR(50),
	PRIMARY KEY(Dnum)
);


CREATE TABLE COURSE
	( Cnum		CHAR(9)		NOT NULL,
	  Title		VARCHAR(30)	NOT NULL,
	  Unit		INT		NOT NULL,
	  Dnum		INT		NOT NULL,
	PRIMARY KEY(Cnum),
	FOREIGN KEY(Dnum) REFERENCES DEPARTMENT(Dnum)
);


CREATE TABLE SECTION
	( Cnum		CHAR(9)		NOT NULL,
	  Snum		INT		NOT NULL,
	  Days	VARCHAR(12),
	  Room		VARCHAR(10),
	  BeginTime		TIME,
	  EndTime		TIME,
	  Capacity		INT,
	  FCWID		CHAR(9)		NOT NULL,
	PRIMARY KEY(Cnum,Snum),
	FOREIGN KEY(Cnum) REFERENCES COURSE(Cnum),
	FOREIGN KEY(FCWID) REFERENCES FACULTY(CWID)
);

CREATE TABLE MATERIAL
(	Cnum CHAR(9) NOT NULL,
	Snum INT NOT NULL,
	FileName varchar(50) NOT NULL,
	Location varchar(150) NOT NULL,
	PRIMARY KEY(Cnum, Snum, FileName),
	FOREIGN KEY(Cnum,Snum) REFERENCES SECTION(Cnum,Snum)
);



CREATE TABLE ENROLL
	( CWID		CHAR(9)		NOT NULL,
	  Cnum		CHAR(9)		NOT NULL,
	  Snum		INT		NOT NULL,
	  Grade		CHAR(2),
	PRIMARY KEY(CWID, Cnum, Snum),
	FOREIGN KEY(CWID) REFERENCES STUDENT(CWID),
	FOREIGN KEY(Cnum,Snum) REFERENCES SECTION(Cnum,Snum)
	
);

CREATE TABLE SCORE_TYPE
(
	Sid INT	NOT NULL,
	SType VARCHAR(20) NOT NULL,
	PRIMARY KEY(Sid)
);



CREATE TABLE GRADE
(	
	Gid			INT			NOT NULL,
	CWID		CHAR(9)		NOT NULL,
	Cnum		CHAR(9)		NOT NULL,
	Snum		INT		NOT NULL,
	Date		DATETIME	NOT NULL,
	Score		INT UNSIGNED NOT NULL,
	SType		INT NOT NULL,
	PRIMARY KEY(CWID,Cnum,Snum,Date),
	FOREIGN KEY(CWID,Cnum,Snum) REFERENCES ENROLL(CWID,Cnum,Snum),
	FOREIGN KEY(SType) REFERENCES SCORE_TYPE(Sid)
);

*
CREATE TABLE STUDENT_FILE
(
	Gid			INT 		NOT NULL,
	FileName varchar(50) NOT NULL,
	Location varchar(150) NOT NULL,
	PRIMARY KEY(Fid),
	FOREIGN KEY(Gid) REFERENCES GRADE(Gid)
	
);

